require: rubocop-rspec

RSpec/BeforeAfterAll:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - sys-proctable.gemspec
    - Gemfile
    - Rakefile
    - examples/*.rb
    - benchmarks/*.rb
Lint/AssignmentInCondition:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - spec/*.rb
Lint/EmptyBlock:
  Exclude:
    - spec/*.rb
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/IfUnlessModifier:
  Enabled: false
Style/RedundantBegin:
  Enabled: false   
Style/SafeNavigation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
Naming/FileName:
  Exclude:
    - 'lib/sys-proctable.rb'
