name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2', '3.3', 'jruby', 'truffleruby']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - ruby-version: truffleruby
            platform: windows-latest
          - ruby-version: jruby
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake

  test_solaris:
    runs-on: ubuntu-latest
    name: A job to run test in Solaris
    steps:
    - uses: actions/checkout@v2
    - name: test Solaris
      id: test
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        prepare: |
          # as far as i know latest possible version ist 2.6.x in Solaris 11.4
          pkgutil -y -i runtime/ruby-26
          ruby -v
          gem install bundler
          bundle install
        run: |
          bundle exec rake
