# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.6, 2.7, 3.0, jruby]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - ruby-version: jruby
            platform: windows-latest
          - ruby-version: 3.0
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake

  # test_solaris:
  #   runs-on: macos-12
  #   name: A job to run test in Solaris
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: test Solaris
  #     id: test
  #     uses: vmactions/solaris-vm@v0
  #     with:
  #       usesh: true
  #       prepare: |
  #         # as far as i know latest possible version ist 2.6.x in Solaris 11.4
  #         pkgutil -y -i runtime/ruby-26
  #         ruby -v
  #         gem install bundler
  #         bundle install
  #         #
  #         # maybe use puppet to get new ruby (?)
  #         # so we would get ruby 2.7.6p219
  #         # curl -JLO 'https://pm.puppetlabs.com/puppet-agent/2021.7.1/7.20.0/repos/solaris/11/puppet7/puppet-agent@7.20.0,5.11-1.i386.p5p'
  #         # pkg install -g file://$(pwd)/puppet-agent\@7.20.0\,5.11-1.i386.p5p pkg:/puppet-agent

  #       run: |
  #         bundle exec rake
